### ISSUE TITLE
AWSAccelerator Pipeline Failed at Prepare and Bootstrap Stage after upgrade to v1.6.3

### ISSUE THREAD

**Issue by de-cx-cloud** [awslabs/landing-zone-accelerator-on-aws#454] opened 2024-05-15 16:25 UTC
**Describe the bug**
After upgrade the LZA to v1.6.3 the SCPs Configuration from AWS TSE-SE Architecture breaks the AWSAccelerator Pipeline at Bootstrap Stage

**To Reproduce**
Run Pipeline after upgrade

**Expected behavior**
Apply SCPs with the AWSAcceleratorPipeline Role

**Please complete the following information about the solution:**

- [ ] Version: v1.6.3

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [X] Region: eu-central-1
- [X] Was the solution modified from the version published on this repository? NO
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [X] Were there any errors in the CloudWatch Logs?

**Screenshots**
![Screenshot 2024-05-15 at 18 22 55](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/160848020/391058c0-3bae-4265-8667-22a17402b712)

**Additional context**
The error message indicates that the user arn:aws:sts::XXXXXX:assumed-role/AWSControlTowerExecution/acceleratorBootstrapCheck does not have permission to perform the ssm:GetParameter action on the resource arn:aws:ssm:eu-central-1:XXXXX:parameter/accelerator/logging/central-bucket/kms/arn.

**Comment by erwaxler** [comment] 2024-05-15 16:33
Hello @de-cx-cloud , thanks for reaching out to the Landing Zone Accelerator team.

The error message indicates this AccessDenied error is a result of the Service Control Policy included in the TSE-SE configuration. Since this error stems from a configuration option and is not related to the Landing Zone Accelerator engine, I'll be closing this issue.  Please feel free to open any issues specific to the TSE-SE configuration using the TSE-SE repository located here: https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-tse-se/issues

Thank you for supporting the Landing Zone Accelerator!

**Closed by erwaxler** 2024-05-15 16:33 UTC
Labels: bug

**Comment by richardkeit** [comment] 2024-06-16 23:38
Hi @erwaxler ,

I raised the same issue for this https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/470 

I've found that there has been a regression when the `strategy` is not defined (explicitly) for the SCP, it has been removing the `AWSFullAccess` SCP.

**Comment by erwaxler** [comment] 2024-06-17 14:15
Hey @richardkeit thank you for calling this out, I was scratching my head on what could be causing that. I'll investigate further and provide an update on #470 when I know more.

Were you able to work-around the issue in the meantime by explicitly setting the strategy?

**Comment by richardkeit** [comment] 2024-06-17 19:06
> Hey @richardkeit thank you for calling this out, I was scratching my head on what could be causing that. I'll investigate further and provide an update on #470 when I know more.
> 
> Were you able to work-around the issue in the meantime by explicitly setting the strategy?

Hi @erwaxler ,
Yes, explicitly setting the strategy works.
