### ISSUE TITLE
Broken CloudWatch Logs Dynamic Partitioning

### ISSUE THREAD

**Issue by StephenBedard** [awslabs/landing-zone-accelerator-on-aws#524] opened 2024-08-06 20:04 UTC
**Describe the bug**
After upgrading to v1.8.1, VPC flow logs are sent to newly named CloudWatch log groups. This breaks the dynamic log partitioning feature of LZA.

**To Reproduce**
1. Make sure VPC flow logs are configured to send to CWL in your LZA config
2. Upgrade to LZA v1.8.1
3. VPC flow logs will no longer be dynamically partitioned by the `${ACCELERATOR_PREFIX}-FirehoseRecordsProcessor` Lambda

**Expected behavior**
Ideally changes made to the logging stack don't change the name of resources (i.e. CW log group names) that customers refer to in their config for dynamic log partitioning. This can be fixed by modifying the log filters file to match the new log group name patterns (see below screenshot).

**Please complete the following information about the solution:**

- [x] Version: v1.8.1

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: ca-central-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
![image](https://github.com/user-attachments/assets/32311a42-fde0-4755-b18b-5e5f9b01cfcb)

**Additional context**

**Comment by hickeydh-aws** [comment] 2024-08-22 18:35
Hello! Thank you for providing this information. Can you please let me know what version of the LZA you upgraded from? I'm trying to see if there were any code changes that may have affected the dynamic log partitioning.

**Comment by hickeydh-aws** [comment] 2024-08-22 20:34
Hello,

I have taken a look at the [commits](https://github.com/awslabs/landing-zone-accelerator-on-aws/commits/release/v1.8.1/) for v1.8.1, and I did not find any changes that could have modified the dynamic log partitioning. I think this particular problem requires a deeper dive into the environment. Can you please cut a ticket to support so that we can continue to diagnose the issue?

**Comment by rycerrat** [comment] 2024-09-24 15:36
Hello,

Thanks for reaching out to the LZA team. I have deep dived this issue and figured out the root cause.

Between the release of LZA v1.6.4 and LZA v.1.7.0, a refactor was done of some networking resources which included a refactor of VPC Flow Logs Log Group creation. Since the LZA does not explicitly pass a name property to the LogGroup construct, the LogGroup name gets created with the default CDK naming convention of:

{Accelerator-Prefix}-NetworkVpcStack-{account}-region-...

Unfortunately, reverting this change would again break the behavior of CW Log Group location for many customers, so this is not a valid approach. In order to address this, we will need to update the `dynamic-partitioning/log-filters.json file to partition with the proper filters:

At a broader level, this will could be applied with something similar to below:

[
  { "logGroupPattern": "AWSAccelerator-NetworkVpcStack*", "s3Prefix": "vpcflowlogs" }
]
or even a bit more granular with a pattern like this:

[
  { "logGroupPattern": "*NetworkVpcStack*VpcFlowLogs*", "s3Prefix": "vpcflowlogs" }
]
A quick note here:

There is not a way to dynamically replace the prefix in the dynamic-partitioning/log-filters.json file, so if you have updated the prefix from AWSAccelerator, please keep this in mind.

Hope this helps!

**Comment by joeldesaulniers** [comment] 2024-10-17 15:09
Based on feedback from @StephenBedard , we are currently working on the internal validation and approval of a merge request into the [LZA CCCS-M configuration repo](https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium).

**Comment by joeldesaulniers** [comment] 2024-11-01 13:11
The following capability was merged into the Landing Zone Accelerator on AWS (LZA) for Canadian Centre for Cyber Security (CCCS) Cloud Medium configuration, release v1.10.0-a:
feat(logging): Added dynamic partitioning rule for CloudWatch Logs VPC Flow Logs

**Comment by rycerrat** [comment] 2024-11-01 13:13
Hey @joeldesaulniers and @StephenBedard!

Going to go ahead and close this out for now since this issue has been resolved. If you need anything else please feel free to reach back out! 

Cheers,
Ryan

**Closed by rycerrat** 2024-11-01 13:13 UTC
Labels: bug
