### ISSUE TITLE
feat: Add support for StackSet ordering

### ISSUE THREAD

**Issue by mbevc1** [awslabs/landing-zone-accelerator-on-aws#593] opened 2024-10-07 08:39 UTC
**Is your feature request related to a problem? Please describe.**
Stacks have support for `runOrder`, but StakcSets don't. So validator doesn't complain but they are not obeyed if used.

**Describe the feature you'd like**
It would be useful to have that feature in case oneo is deploying dependant customisations.

**Additional context**
n/a

**Comment by erwaxler** [comment] 2024-10-08 14:13
Hi @mbevc1 , thanks for reaching out to the Landing Zone Accelerator team. I'm closing this issue as a duplicate of #63, I have reopened the issue and it is planned to be included in our next release. Please follow issue #63 for updates. Thank you for your support of the Landing Zone Accelerator!

**Closed by erwaxler** 2024-10-08 14:13 UTC
Labels: duplicate, enhancement

**Comment by mbevc1** [comment] 2024-10-08 14:27
Thanks @erwaxler ! Do you have a roadmap or timelines for new releases and features?

**Comment by erwaxler** [comment] 2024-10-08 14:41
@mbevc1 The roadmap is not publicly available, the v1.10.0 release is planned for later this month. If you have questions on specific features, please reach out to your Solutions Architect or Technical Account Manager.

**Comment by mbevc1** [comment] 2024-10-08 14:53
Thanks @erwaxler ! Unless there are people directly to reach out I'll check with our PSA.
