### ISSUE TITLE
Creating AWS Account with LZA requires manual intervention

### ISSUE THREAD

**Issue by twdcnz** [awslabs/landing-zone-accelerator-on-aws#222] opened 2023-08-01 03:51 UTC
**Describe the bug**
When creating a new AWS account using LZA manual intervention is required using the Control Tower console. It seems like LZA doesn't populate the IAM Identity Center details of the new account, which prevents it being automated. See details in "actual behavior" below.

**To Reproduce**
Ensure you have a new working email address for the new AWS account (inside corporate this means creating a new alias / mailing list / etc)
Create the new account configuration in the accounts-config.yaml file (see below)
Create a new VPC for the new AWS account in the network-config.yaml file (probably not necessary to reproduce the problem)
Check in your code and run the AWSAccelerator-Pipeline

```
workloadAccounts:
(existing accounts)
  - name: DevOps
    description: DevOps Account
    email: devops@example.com
    organizationalUnit: Infrastructure
```

**Expected behavior**
A new AWS account is created and added to the AWS Organisation.

**Actual behavior**

Prepare Phase of the **pipeline** cuts off suddenly

`AWSAccelerator-PrepareStack-855200000000-ap-southeast-2: creating CloudFormation changeset...
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 0/10 | 4:40:42 AM | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack                         | AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 User Initiated
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 0/10 | 4:40:50 AM | UPDATE_IN_PROGRESS   | Custom::GetPortfolioId                             | GetPortFolioId/Resource/Default (GetPortFolioId5CA7347E) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 0/10 | 4:40:50 AM | UPDATE_IN_PROGRESS   | Custom::LoadAcceleratorConfigTable                 | LoadAcceleratorConfigTable/Resource/Default (LoadAcceleratorConfigTable8F9D29D6) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 1/10 | 4:40:55 AM | UPDATE_COMPLETE      | Custom::GetPortfolioId                             | GetPortFolioId/Resource/Default (GetPortFolioId5CA7347E) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 1/10 | 4:41:02 AM | UPDATE_IN_PROGRESS   | Custom::LoadAcceleratorConfigTable                 | LoadAcceleratorConfigTable/Resource/Default (LoadAcceleratorConfigTable8F9D29D6) Requested update required the provider to create a new physical resource
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 2/10 | 4:41:02 AM | UPDATE_COMPLETE      | Custom::LoadAcceleratorConfigTable                 | LoadAcceleratorConfigTable/Resource/Default (LoadAcceleratorConfigTable8F9D29D6) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 2/10 | 4:41:04 AM | UPDATE_IN_PROGRESS   | Custom::ValidateEnvironmentConfig                  | ValidateEnvironmentConfig/Resource/Default (ValidateEnvironmentConfigB40B464F) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 2/10 | 4:41:05 AM | UPDATE_IN_PROGRESS   | Custom::CreateOrganizationalUnits                  | CreateOrganizationalUnits/Resource/Default (CreateOrganizationalUnits3A58A65B) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 3/10 | 4:41:11 AM | UPDATE_COMPLETE      | Custom::CreateOrganizationalUnits                  | CreateOrganizationalUnits/Resource/Default (CreateOrganizationalUnits3A58A65B) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 3/10 | 4:41:13 AM | UPDATE_IN_PROGRESS   | Custom::InviteAccountsToOrganization               | InviteAccountsToOu/Resource/Default (InviteAccountsToOu482336A1) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 4/10 | 4:41:16 AM | UPDATE_COMPLETE      | Custom::InviteAccountsToOrganization               | InviteAccountsToOu/Resource/Default (InviteAccountsToOu482336A1) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 5/10 | 4:41:37 AM | UPDATE_COMPLETE      | Custom::ValidateEnvironmentConfig                  | ValidateEnvironmentConfig/Resource/Default (ValidateEnvironmentConfigB40B464F) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 5/10 | 4:41:59 AM | UPDATE_IN_PROGRESS   | Custom::CreateOrganizationAccounts                 | CreateOrganizationAccounts/Resource/Default (CreateOrganizationAccounts49A5350C) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 6/10 | 4:42:04 AM | UPDATE_COMPLETE      | Custom::CreateOrganizationAccounts                 | CreateOrganizationAccounts/Resource/Default (CreateOrganizationAccounts49A5350C) 
AWSAccelerator-PrepareStack-855200000000-ap-southeast-2 | 6/10 | 4:42:29 AM | UPDATE_IN_PROGRESS   | Custom::CreateControlTowerAccounts                 | CreateCTAccounts/Resource/Default (CreateCTAccounts3049A752) 
6/10 Currently in progress: AWSAccelerator-PrepareStack-855200000000-ap-southeast-2, CreateCTAccounts3049A752`

In **CloudFormation** Stack "AWSAccelerator-PrepareStack-855200000000-ap-southeast-2" I found this message

`Received response status [FAILED] from custom resource. Message returned: Error: AWS Account removed@example.com is TAINTED state. Message: AWS Control Tower cannot complete the operation because activation of account 29500000000 is not complete. Try again in one hour. If this error persists, contact AWS Support.. Check Service Catalog at dTt (/var/task/index.js:57:21054) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Runtime.handler (/var/task/__entrypoint__.js:1:932) (RequestId: 10c2803c-8c73-4cff-90b1-36bdde38857b)`

This led me to **Service Catalog**

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/91913779/01dc8663-fdeb-4f3b-b7ec-1852d4e17e63)

The detail in **Service Catalog** says

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/91913779/74d656e0-f1a3-4c35-a2b4-b957777a0e91)

The Solution in **Control Tower** was 

- Select Organization from the left menu
- Click the radio button beside the new account, then from the action menu choose update
- The "Access Configuration" section was empty. I copied the email address from the account email field into the "IAM Identity Center user email" field then made up a user name. I hit ok then waited a half hour.
- I rolled the CloudFormation stack back, which required using the advanced options to skip the resource that wouldn't roll back cleanly, then I ran the pipeline again.

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/91913779/a9b3ed7f-5bdd-4e0d-87d1-c913bdc39f70)

**Please complete the following information about the solution:**

- [X] Version: 1.4.2
- [X] Region: ap-southeast-2
- [X] Was the solution modified from the version published on this repository? No
- [X] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- [X] Were there any errors in the CloudWatch Logs? No

**Screenshots**
As above

**Additional context**
This was in an existing LZA / Control tower setup.

**Comment by nagmesh** [comment] 2023-08-02 18:04
Hello @twdcnz,

Thank you for reaching out to us. 
I was unable to reproduce the issue at my end. My accounts were enrolled in CT and account factory.
Are all your accounts ending in tainted state? Under the hood, LZA calls the Account Factory for Control Tower in service catalog and onboards the account based on the input. 
There could be an [underlying reason](https://docs.aws.amazon.com/controltower/latest/userguide/troubleshooting.html#unable-to-update-account) why the account went to tainted state. But if its consistent even in new accounts then please raise a ticket with AWS Support for help in troubleshooting the issue under Control Tower > Account Factory.
I hope this was helpful! I will be closing this issue, but please feel free to follow-up or open new issues as you have additional questions. Thank you for your interest in Landing Zone Accelerator!

**Closed by nagmesh** 2023-08-02 18:04 UTC
Labels: bug

**Comment by twdcnz** [comment] 2023-08-02 18:57
Thanks for looking nagmesh. I'll not able to create another account in the organisation at the moment, but there will be another account created at some point. If we have a similar problem next time it happens I'll reach out to AWS Support
