### ISSUE TITLE
'excludedAccounts' has no effect on SCP deploymentTargets

### ISSUE THREAD

**Issue by FarrOut** [awslabs/landing-zone-accelerator-on-aws#443] opened 2024-05-01 06:54 UTC
**Describe the bug**
When applying [serviceControlPolicies](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.OrganizationConfig.html#serviceControlPolicies) in [DeploymentTargets](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.DeploymentTargets.html), the [excludedAccounts](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.DeploymentTargets.html#excludedAccounts) property has no effect on SCPs applied to accounts.

**To Reproduce**

*accounts-config.yaml*
``` yaml
mandatoryAccounts:
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this
      mandatory account. Note, the account name key does not need to match the
      AWS account name.
    email: lza_admin@example.com
    organizationalUnit: Root
    warm: false
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory
      account. Note, the account name key does not need to match the AWS account
      name.
    email: lza_logs@example.com
    organizationalUnit: Security
    warm: false
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not
      change the name field for this mandatory account. Note, the account name
      key does not need to match the AWS account name.
    email: lza_audit@example.com
    organizationalUnit: Security
    warm: false
workloadAccounts:
  - name: John
    description: Imagine.
    email: john@example.com
    organizationalUnit: Infrastructure
  - name: George
    description: Set on you
    email: george@example.com
    organizationalUnit: Infrastructure
  - name: Paul
    description: Let it be
    email: paul@example.com
    organizationalUnit: Infrastructure
  - name: Ringo
    description: All by myself
    email: ringo@example.com
    organizationalUnit: Infrastructure
```

*organization-config.yaml*
``` yaml
enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
serviceControlPolicies:
  - name: AcceleratorGuardrails1
    description: >
      Accelerator GuardRails 1
    policy: service-control-policies/guardrails-1.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Infrastructure
        - Security
      excludedAccounts:
        - Ringo
taggingPolicies: []
backupPolicies: []
```

Copy  (guardrails-1.json)[https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/reference/sample-configurations/lza-sample-config/service-control-policies/guardrails-1.json] to ```./service-control-policies/``` in CodeCommit repo.

**Expected behavior**
SCP called ```AcceleratorGuardrails1``` should be attached to accounts ```John```,```George```,```Paul```, but not ```Ringo```.

**Please complete the following information about the solution:**

- [ ] Version: **v1.6.2**
- [ ] Region: Tested on **eu-west-1 & ap-southeast-2**
- [ ] Was the solution modified from the version published on this repository? **No**
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**

**Additional context**

**Comment by erwaxler** [comment] 2024-05-01 15:24
Hi @FarrOut , thanks for reaching out to the Landing Zone Accelerator team!

This is the expected behavior. The Service Control Policies (SCPs) deployed by LZA don't work any differently than what happens natively out of the box for AWS Org: 
https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_evaluation.html

When you target an OU (via), LZA will attach the specific SCP to that OU. If the SCP is Deny method, then all Accounts (included Nested OUs) will be affected by the Deny statement in the OU where the SCP is attached.  Because the SCP is being attached to the OU, the excludedAccounts portion won't matter at all as the SCP is not being attached to the individual Account.

If you want to apply that SCP to accounts in the Infrastructure OU, but not to the Ringo account, you have two options:
1. Move the Ringo account to a different organizational unit.
2. Instead of setting deploymentTargets to the OU, have the Service Control Policies target individual accounts.

I'll be closing this issue as this is the expected behavior, thanks again for supporting the Landing Zone Accelerator!

**Closed by erwaxler** 2024-05-01 15:24 UTC
Labels: bug
