### ISSUE TITLE
Code Pipeline fails using reference sample config

### ISSUE THREAD

**Issue by AndyN16** [awslabs/landing-zone-accelerator-on-aws#5] opened 2022-07-20 10:36 UTC
**Describe the bug**
Code Pipeline Prepare stage failed with error message

[Container] 2022/07/19 13:22:49 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi. Reason: exit status 1

**To Reproduce**
After initial deployment of landing-zone-accelerator I then utilised the reference sample configuration, replacing aws region and email addresses in the relevanlt configuration yaml files.
I then went to the codepipline and performed a release change

**Expected behavior**
Using the reference sample configuration I expected the codepipeline to deploy the relevant configuration

**Please complete the following information about the solution:**
- [Version: v1.0.1

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [ ] Region: sa-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? No.. Is there any particular service and I need to check
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by rgd11** [comment] 2022-08-01 19:24
Thank you @anyunt for reporting this issue.

Please provide more info from the failed AWS CodeBuild logs. Specifically, earlier in the logs, you should see some error messages that can clue you into what happened.

**Comment by djer34** [comment] 2022-09-23 20:12
Is there any update to this? I'm getting the same error on the same step with the latest version (1.2.0). Here is the log file with a bit more information. Same error though.

[Log.txt](https://github.com/awslabs/landing-zone-accelerator-on-aws/files/9636840/Log.txt)

**Comment by boyobejamin** [comment] 2022-09-27 13:07
Same here with similar log outputs.

**Comment by djer34** [comment] 2022-09-27 15:33
@boyobejamin I managed to fix this. I had the wrong emails entered when using the CloudFormation template. Steps I took to fix this:

1. Make sure everything is cleared from any previous AWS LZ accelerator CloudFormation stack running. If there are any leftover resources, things will fail (leftover pipelines, SNS policies, S3 buckets, etc.).
2. Use AWS Control Tower, and create a basic landing zone with an Audit and Log Archive account (walk through the default steps). Use unique emails for these accounts.
3. Use the CloudFormation LZ accelerator template. When it asks for emails, make sure everything matches. Management account email is listed in Control Tower, same with Audit and Log Archive accounts. The 'Approval' email can be whatever you want. Just use your own.

It is a weird fix, but that's what worked for me. I hope this helps. And don't use AWS Organizations. Use Control Tower.

**Comment by boyobejamin** [comment] 2022-09-27 22:45
Amazing. Good call out @djer34 , I had initially setup different groups so certain folks could opt in or out of specific categories of messaging/access.

I was able to get farther by setting them all to the same addr.

**Comment by dhouse-RockITek** [comment] 2022-09-28 11:47
> @boyobejamin I managed to fix this. I had the wrong emails entered when using the CloudFormation template. Steps I took to fix this:
> 
> 1. Make sure everything is cleared from any previous AWS LZ accelerator CloudFormation stack running. If there are any leftover resources, things will fail (leftover pipelines, SNS policies, S3 buckets, etc.).
> 2. Use AWS Control Tower, and create a basic landing zone with an Audit and Log Archive account (walk through the default steps). Use unique emails for these accounts.
> 3. Use the CloudFormation LZ accelerator template. When it asks for emails, make sure everything matches. Management account email is listed in Control Tower, same with Audit and Log Archive accounts. The 'Approval' email can be whatever you want. Just use your own.
> 
> It is a weird fix, but that's what worked for me. I hope this helps. And don't use AWS Organizations. Use Control Tower.

I have the same issue - deploying on top of existing ControlTower deployment.  I copied the email addresses from the ControlTower config for MGMT, Audit and Log Archive accounts in the CloudFormation template.  Used the same email for MGMT and "Manual Approval Stage notification email list" - not sure what I'm supposed to do here?  Docs say LZA builds on top of an existing Control Tower - any suggestions for troubleshooting?

**Comment by djer34** [comment] 2022-09-29 02:43
> I have the same issue - deploying on top of existing ControlTower deployment. I copied the email addresses from the ControlTower config for MGMT, Audit and Log Archive accounts in the CloudFormation template. Used the same email for MGMT and "Manual Approval Stage notification email list" - not sure what I'm supposed to do here? Docs say LZA builds on top of an existing Control Tower - any suggestions for troubleshooting?

The only thing I can think of is maybe to use a different email for the "Manual Approval Stage." I am speculating, but perhaps this needs to be a different email than the Management account. Furthermore, this step is optional altogether. Try just leaving it blank; it won't ask for approval and will continue the pipeline.

**Comment by dhouse-RockITek** [comment] 2022-09-29 12:12
Here are the full logs for the AWSAccelerator-ToolkitProject Build phase:

[Container] 2022/09/29 11:36:36 going inside waitForAgent
[Container] 2022/09/29 11:36:36 Waiting for agent ping
[Container] 2022/09/29 11:36:37 Waiting for DOWNLOAD_SOURCE
[Container] 2022/09/29 11:36:54 Phase is DOWNLOAD_SOURCE
[Container] 2022/09/29 11:36:54 finished waitForAgent
[Container] 2022/09/29 11:36:54 inside CopySrc
[Container] 2022/09/29 11:36:54 CODEBUILD_SRC_DIR=/codebuild/output/src193/src/s3/00
[Container] 2022/09/29 11:36:54 CODEBUILD_SRC_DIR_Config=/codebuild/output/src193/src/s3/01
[Container] 2022/09/29 11:36:54 finished CopySrc
[Container] 2022/09/29 11:36:54 YAML location is /codebuild/readonly/buildspec.yml
[Container] 2022/09/29 11:36:54 No commands found for phase name: install
[Container] 2022/09/29 11:36:54 Setting HTTP client timeout to higher timeout for S3 source
[Container] 2022/09/29 11:36:54 Processing environment variables
[Container] 2022/09/29 11:36:54 Selecting 'nodejs' runtime version '14' based on manual selections...
[Container] 2022/09/29 11:36:54 Running command echo "Installing Node.js version 14 ..."
Installing Node.js version 14 ...

[Container] 2022/09/29 11:36:54 Running command n $NODE_14_VERSION
     copying : node/14.19.2
   installed : v14.19.2 (with npm 6.14.17)

[Container] 2022/09/29 11:37:29 Moving to directory /codebuild/output/src193/src/s3/00
[Container] 2022/09/29 11:37:29 Configuring ssm agent with target id: codebuild:f6b9d1f4-4a01-4f95-af45-e425174ccc8a
[Container] 2022/09/29 11:37:29 Successfully updated ssm agent configuration
[Container] 2022/09/29 11:37:29 Registering with agent
[Container] 2022/09/29 11:37:29 Phases found in YAML: 2
[Container] 2022/09/29 11:37:29  INSTALL: 0 commands
[Container] 2022/09/29 11:37:29  BUILD: 6 commands
[Container] 2022/09/29 11:37:29 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
[Container] 2022/09/29 11:37:29 Phase context status code:  Message: 
[Container] 2022/09/29 11:37:29 Entering execCommands
[Container] 2022/09/29 11:37:29 Entering phase INSTALL
[Container] 2022/09/29 11:37:29 Phase complete: INSTALL State: SUCCEEDED
[Container] 2022/09/29 11:37:29 Phase context status code:  Message: 
[Container] 2022/09/29 11:37:29 Entering phase PRE_BUILD
[Container] 2022/09/29 11:37:29 Phase complete: PRE_BUILD State: SUCCEEDED
[Container] 2022/09/29 11:37:29 Phase context status code:  Message: 
[Container] 2022/09/29 11:37:30 Entering phase BUILD
[Container] 2022/09/29 11:37:30 Running command env
GOLANG_15_VERSION=1.15.15
MAVEN_OPTS=-Dmaven.wagon.httpconnectionManager.maxPerRoute=2
CODEBUILD_LAST_EXIT=0
CODEBUILD_START_TIME=1664451332410
GOLANG_16_VERSION=1.16.15
ACCELERATOR_QUALIFIER=aws-accelerator
CODEBUILD_BMR_URL=https://CODEBUILD_AGENT:3000
NODE_12_VERSION=12.22.12
JRE_8_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto/jre
CODEBUILD_SOURCE_VERSION=arn:aws:s3:::aws-accelerator-pipeline-<accountId>-us-east-1/AWSAccelerator-Pipel/Build/sIlATih
CODEBUILD_AGENT_ENDPOINT=http://127.0.0.1:7831
HOSTNAME=1cd47328b5b8
CODEBUILD_BUILD_ID=AWSAccelerator-ToolkitProject:f6b9d1f4-4a01-4f95-af45-e425174ccc8a
CODEBUILD_KMS_KEY_ID=arn:aws:kms:us-east-1:<accountId>:key/5c7c1881-01db-4e25-a3e1-ed7030518577
NODE_14_VERSION=14.19.2
JRE_11_HOME=/usr/lib/jvm/java-11-amazon-corretto
HOME=/root
OLDPWD=/codebuild/readonly
JRE_HOME=/usr/lib/jvm/java-11-amazon-corretto
CODEBUILD_GOPATH=/codebuild/output/src193
CODEBUILD_CI=true
GOENV_DISABLE_GOPATH=1
CODEBUILD_BUILD_NUMBER=1
CODEBUILD_BUILD_SUCCEEDING=1
NODE_OPTIONS=--max_old_space_size=4096
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/v2/credentials/5b7389ba-a1fc-4b2a-8905-e90781b77134
CODEBUILD_BUILD_ARN=arn:aws:codebuild:us-east-1:<accountId>:build/AWSAccelerator-ToolkitProject:f6b9d1f4-4a01-4f95-af45-e425174ccc8a
LC_CTYPE=C.UTF-8
AWS_EXECUTION_ENV=AWS_ECS_EC2
ACCELERATOR_STAGE=prepare
RUBY_BUILD_SRC_DIR=/usr/local/rbenv/plugins/ruby-build
DOTNET_5_SDK_VERSION=5.0.408
CODEBUILD_INITIATOR=codepipeline/AWSAccelerator-Pipeline
CODEBUILD_SOURCE_REPO_URL_Config=arn:aws:s3:::aws-accelerator-pipeline-<accountId>-us-east-1/AWSAccelerator-Pipel/Config/t7VPE2E
AWS_DEFAULT_REGION=us-east-1
PHP_80_VERSION=8.0.18
ECS_CONTAINER_METADATA_URI_V4=http://169.254.170.2/v4/790499fa-c213-4751-97a4-75dff5542dcc
PHP_73_VERSION=7.3.33
ECS_CONTAINER_METADATA_URI=http://169.254.170.2/v3/790499fa-c213-4751-97a4-75dff5542dcc
DOTNET_ROOT=/root/.dotnet
PHP_74_VERSION=7.4.29
CODEBUILD_SRC_DIR_Config=/codebuild/output/src193/src/s3/01
CODEBUILD_EXECUTION_ROLE_BUILD=
DOTNET_31_SDK_VERSION=3.1.419
PATH=/usr/local/bin/sbt/bin:/root/.phpenv/shims:/root/.phpenv/bin:/root/.goenv/shims:/root/.goenv/bin:/go/bin:/root/.phpenv/shims:/root/.phpenv/bin:/root/.pyenv/shims:/root/.pyenv/bin:/root/.rbenv/shims:/usr/local/rbenv/bin:/usr/local/rbenv/shims:/root/.dotnet/:/root/.dotnet/tools/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/tools:/codebuild/user/bin
RUBY_26_VERSION=2.6.10
CODEBUILD_LOG_PATH=f6b9d1f4-4a01-4f95-af45-e425174ccc8a
RUBY_27_VERSION=2.7.6
PYYAML_VERSION=5.4.1
CDK_OPTIONS=deploy --stage prepare
CODEBUILD_BUILD_IMAGE=aws/codebuild/standard:5.0
GOPATH=/go:/codebuild/output/src193
AWS_REGION=us-east-1
CODEBUILD_BUILD_URL=https://us-east-1.console.aws.amazon.com/codebuild/home?region=us-east-1#/builds/AWSAccelerator-ToolkitProject:f6b9d1f4-4a01-4f95-af45-e425174ccc8a/view/new
JAVA_8_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto
CODEBUILD_SRC_DIR=/codebuild/output/src193/src/s3/00
CODEBUILD_PROJECT_UUID=ce70750f-3261-460f-b228-83012c03e657
CDK_NEW_BOOTSTRAP=1
CODEBUILD_CONTAINER_NAME=default
CODEBUILD_AUTH_TOKEN=c091476e-ed06-4705-bc87-b75124ef3dd2
JAVA_11_HOME=/usr/lib/jvm/java-11-amazon-corretto
JDK_8_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto
LOG4J_UNSAFE_VERSIONS=2.11.1 1.2.8
JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto
PWD=/codebuild/output/src193/src/s3/00
CODEBUILD_FE_REPORT_ENDPOINT=https://codebuild.us-east-1.amazonaws.com/
PYTHON_37_VERSION=3.7.13
PYTHON_38_VERSION=3.8.13
PYTHON_39_VERSION=3.9.12
JDK_11_HOME=/usr/lib/jvm/java-11-amazon-corretto
CONFIG_COMMIT_ID=70b0d3b4d34a35c629f473000f598944410542a6
NUGET_XMLDOC_MODE=skip
JDK_HOME=/usr/lib/jvm/java-11-amazon-corretto

[Container] 2022/09/29 11:37:30 Running command cd source

[Container] 2022/09/29 11:37:30 Running command cd packages/@aws-accelerator/accelerator

[Container] 2022/09/29 11:37:30 Running command if [ -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi

[Container] 2022/09/29 11:37:30 Running command if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi
yarn run v1.22.19
$ /codebuild/output/src193/src/s3/00/source/packages/@aws-accelerator/accelerator/node_modules/.bin/ts-node --transpile-only cdk.ts synth --stage prepare --require-approval never --config-dir /codebuild/output/src193/src/s3/01 --partition aws
[2022-09-29 11:37:31] - info:       [toolkit] Executing cdk synth prepare
[2022-09-29 11:37:58] - info:       [app] Begin Accelerator CDK App
[2022-09-29 11:37:59] - error:  undefined
Subprocess exited with error 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[Container] 2022/09/29 11:37:59 Command did not exit successfully if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi exit status 1
[Container] 2022/09/29 11:37:59 Phase complete: BUILD State: FAILED
[Container] 2022/09/29 11:37:59 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi. Reason: exit status 1
[Container] 2022/09/29 11:37:59 Entering phase POST_BUILD
[Container] 2022/09/29 11:37:59 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2022/09/29 11:37:59 Phase context status code:  Message:

**Comment by djer34** [comment] 2022-10-03 23:10
@sttomm Well, I'm back, and now having the exact same issue you are. When trying to modify the accounts-config.yaml file to add accounts, it fails when pushing the update through CodePipeline. Did you find a solution to this? I'll keep messing with it in the meantime.

**Comment by sttomm** [comment] 2022-10-04 07:15
Thanks for your reply @djer34. As you face the same issue, it looks more like a general one. Before, I was wondering whether we did some strange config of Control Tower in our Test Environment where i am trying to roll it out. Sadly i wasn't able to make any progress on figuring out what causes that issue.

**Comment by djer34** [comment] 2022-10-04 17:01
@sttomm I might have found my problem. After rolling back the stack and trying again, I got a different error. It seems that I have reached my max number of accounts of 10 in my organization, and Control Tower cannot create new ones. So I had to request an increase through service quotas to raise my limit. Weird it didn't tell me this the first time, but I thought this could also be your issue.

![2022-10-04_10-58-09](https://user-images.githubusercontent.com/114241228/193881026-a09547da-57e1-4bb0-b3d9-c6750daafb62.jpg)

**Comment by sttomm** [comment] 2022-10-10 10:11
Thanks for that tip @djer34. Sadly it did not help in our situation. It seems like we are running into some other issue around AWS Control Tower permissions.
But perhaps you can help us in finding the more detailed log you showed in the previous comment. Where did you get that one from? Was ii just listed in the Stack logs, the CloudWatch logs, or is it from a specific Services's CloudTrail logs? Or from somewhere else?

**Comment by djer34** [comment] 2022-10-11 00:25
@sttomm Well, sadly even after increasing my max number of accounts, I'm still getting the same error. I even started all the way over, completely rolling back all the stacks, deleting S3 buckets, etc. Now I'm getting this error, doesn't make sense.

My previous comment was just from the CodeBuild Build Logs. However, I'm not getting that anymore, I'm back to getting the same error you are currently getting as mentioned above.

Any more to this? Why do you think it is a permissions error with Control Tower?

**Comment by sttomm** [comment] 2022-10-11 07:04
I assume it's a permission error, as i found the following INFO log in the CloudWatch logs, as mentioned in one of my previous comments:

`Provisioning failure error message: Account Factory has insufficient permission to baseline AWS SSO`

It is only an INFO log, but it still sounds to me like it could be the root cause. Not sure though what is meant with baselining AWS SSO here.

**Comment by djer34** [comment] 2022-10-11 17:36
@sttomm Ya I see that now after reviewing your log screenshot from your other post. That's odd. Well I dug more into the Lambda CloudWatch log and figured that my problem is still due to the fact that the accelerator thinks I'm at my max account limit of 10. When in fact, I increased in through quotas to beyond 10 and it still gives me this error:
![image](https://user-images.githubusercontent.com/114241228/195160796-65f199bd-13a9-4861-b01f-9814aecaa49e.png)

Very strange, its like it sees only the default parameter. It sucks because I'm actually not trying to create anymore accounts at all, I'm trying to use previously created accounts and point the accelerator at those. Quite frustrating.

**Comment by gregorycoleman** [comment] 2022-11-14 18:53
@dhouse-RockITek Did you find a solution ?

**Comment by boyobejamin** [comment] 2022-11-19 03:39
Using the latest template, v1.2.2 I am able to get farther in the deployment.

Compared to previous versions, the account email addresses for auditing, logging, and mgmt must not only be unique but match what already exists in AWS Organizations.

**Comment by StoneColdCodez** [comment] 2022-12-12 13:25
> @sttomm Ya I see that now after reviewing your log screenshot from your other post. That's odd. Well I dug more into the Lambda CloudWatch log and figured that my problem is still due to the fact that the accelerator thinks I'm at my max account limit of 10. When in fact, I increased in through quotas to beyond 10 and it still gives me this error: ![image](https://user-images.githubusercontent.com/114241228/195160796-65f199bd-13a9-4861-b01f-9814aecaa49e.png)
> 
> Very strange, its like it sees only the default parameter. It sucks because I'm actually not trying to create anymore accounts at all, I'm trying to use previously created accounts and point the accelerator at those. Quite frustrating.

I ran into the account limit error as well.  It was increased 3 days ago.  Retrying the prepare stage or restarting the pipeline results in the same error (below).   @djer34 Did you get past the account error?

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named AWSAccelerator-PrepareStack-XXXXXXXXX-us-east-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: AWS Account aws+redacted@redacted.com is in ERROR state. Message: AWS Control Tower cannot create an account because you have reached the limit on the number of accounts in your organization.. Check Service Catalog

I haven't found the account state yet.  I'll hit AWS support and start digging.

**Comment by djer34** [comment] 2023-01-05 01:34
@StoneColdCodez 

Unfortunately not. What I ended up doing, unfortunately, was completely starting over. My company created a new AWS organization with Control Tower and started from scratch.

**Closed** 2023-02-14 21:02 UTC
Labels: bug, response requested
