### ISSUE TITLE
Update to v1.5.0 from 1.4.3 have significant issues.

### ISSUE THREAD

**Issue by DonthineniSagar** [awslabs/landing-zone-accelerator-on-aws#285] opened 2023-10-17 09:23 UTC
**Describe the bug**
We would like update LZA version to 1.5.0 

**To Reproduce**
Update to LZA 1.5.0 from 1.4.3

**Expected behavior**
A complete update without issues
**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.4.3]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [ ] Region: ap-southeast-2
- [ ] Was the solution modified from the version published on this repository?N
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?NA
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? NA
- [ ] Were there any errors in the CloudWatch Logs? NA

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
We have Custom NACLs created in Network Config file and attached to VPCs, during the update process. The pipeline was failing due to the NACL association was already existing, deleting the custom NACL and running the pipeline worked for NACLs. However it became inconsistent with TGW attachement and failed. is this expected?

Thanks,
Sagar

**Comment by padebnat** [comment] 2023-10-17 18:21
Hello @DonthineniSagar , 
Thank you for reaching out to the Landing Zone Accelerator team!
I wanted to let you know that we have added an item in our backlog to look into this issue.

Thank you for your support and interest of the LZA solution! I will leave this issue open should you have any follow-ups for the team, and we will update you when the issue is fixed.

**Comment by bo1984** [comment] 2023-10-17 18:29
@DonthineniSagar can you provide the error that you're getting and in which Network stack you're getting this error? NACLs should not have any effect on the TGW attachments.

**Comment by awsclemj** [comment] 2023-10-18 08:10
The NACL issue appears to be related to an upstream issue in the CDK library. Relating that bug report here for reference — https://github.com/aws/aws-cdk/issues/27476

**Comment by DonthineniSagar** [comment] 2023-10-18 09:47
Thanks for the response, since it was test LZA, i tried removing NACL and LZA proceeded without an issue creating the NACL again, however this is not going to be a valid work around in Production LZA.

Can we safely revert back to 1.4.3 on test? as we need to have the test LZA on same as prod, test platform related changes.

Thank you! appreciate your help.

**Comment by richardkeit** [comment] 2024-03-19 02:18
Hi @awsclemj , I reckon close this one out 🎉

**Closed** 2024-06-19 15:15 UTC
Labels: bug
