### ISSUE TITLE
The accelerator does not take + sign in email id

### ISSUE THREAD

**Issue by spate007** [awslabs/landing-zone-accelerator-on-aws#69] opened 2023-02-19 02:08 UTC
**Describe the bug**
The accelerator does not take + sign in email id

**To Reproduce**
Use any email with + sign in the config file e.g. john.test+21@gmail.com

**Expected behavior**
The accelerator should work with + sign in email id in config

**Please complete the following information about the solution:**

-1.3

 [config-validator] Error: accounts-config.yaml has 8 issues: Invalid email XXX.XXXX+1@mow.com <----- UPDATE EMAIL ADDRESS.

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by sachinpate007** [comment] 2023-02-19 03:15
THe issue was in the syntax

**Comment by erwaxler** [comment] 2023-02-19 18:30
@sachinpate007 Thank you for your interest in the Landing Zone Accelerator on AWS! I was unable to reproduce this error. Can you elaborate on your comment regarding the syntax? If the error was syntactical and unrelated to `+` characters in the account email addresses I'll go ahead and close this issue.

**Comment by sachinpate007** [comment] 2023-02-19 19:58
Yes, You can close the issue. I have another issue related to 
accountIds:
  - email: <anding-zone-management-email@example.com
    accountId: "000000000000 "
  - email: test@example.com
    accountId: "111111111111"

If I add above to account config, the pipeline fails in prepare step:


[Container] 2023/02/19 15:54:01 Running command if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi
--
118 | yarn run v1.22.19
119 | $ /codebuild/output/src575/src/s3/00/source/packages/@aws-accelerator/accelerator/node_modules/.bin/ts-node --transpile-only cdk.ts synth --stage prepare --require-approval never --config-dir /codebuild/output/src575/src/s3/01 --partition aws
120 | [2023-02-19 15:54:03] - info:       [toolkit] Executing cdk synth prepare
121 | [2023-02-19 15:54:35] - info:       [app] Begin Accelerator CDK App
122 | [2023-02-19 15:54:37] - error:  undefined
123 | [2023-02-19 15:54:37] - error:  undefined
124 | Subprocess exited with error 1
125 | error Command failed with exit code 1.
126 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
127 |  
128 | [Container] 2023/02/19 15:54:37 Command did not exit successfully if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi exit status 1
129 | [Container] 2023/02/19 15:54:37 Phase complete: BUILD State: FAILED
130 | [Container] 2023/02/19 15:54:37 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi. Reason: exit status 1

Also will accelerator create network in existing workload accounts? (I have created workload accounts using service catalogue and control tower).
Also there are some existing accounts in my root which I want to ignore when applying landing zone. What is the syntax or example to ignore accounts?

**Comment by erwaxler** [comment] 2023-02-22 16:20
@spate007 Please reserve GitHub issues for distinct, reproducible errors rather than general troubleshooting.  To answer your questions:

- The account Id should not be included in the `accounts-config.yaml` file. Please see [here](https://catalog.workshops.aws/landing-zone-accelerator/en-US/lza-administrators/initial-customization/organizational-structure/adding-aws-account-to-config-file).
- Network resources are only deployed to accounts and organizational units specified in the `network-config.yaml` file.
- To ignore accounts, move them to an Organizational Unit with the `ignored` property set to true. Please see [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.OrganizationalUnitConfig.html).

Here are additional resources to learn about LZA:

[Implementation Guide](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/solution-overview.html)
[Immersion Day Workshop](https://catalog.workshops.aws/landing-zone-accelerator/en-US)
[TypeDocs](https://awslabs.github.io/landing-zone-accelerator-on-aws/modules/_aws_accelerator_config.html)

For additional assistance, please open a case with [AWS Support](https://support.console.aws.amazon.com/support/home#).

**Closed by erwaxler** 2023-02-22 16:20 UTC
Labels: bug, response requested
