### ISSUE TITLE
Centralized Logging does not utilize wildcard * in dynamic partition filtering

### ISSUE THREAD

**Issue by mmacaula** [awslabs/landing-zone-accelerator-on-aws#284] opened 2023-10-17 02:41 UTC
**Describe the bug**
The wildcard is not used and is instead used as a direct string match.  Removing the wildcard from the filter causes filter to pass. 

**To Reproduce**
Deploy LZA, use globalConfig -> logging -> cloudwatchlogs -> dynamicPartitioning to setup a dynamic partition and specify a `*` (ex: `/some/log/gro*` in the `logGroupPattern` field.   In a workload account, create a log group with that pattern and a `*` (ex: `/some/log/group`.  Deploy, create log group in target account, no logs will be sent to S3.

If you update the `logGroupPattern` to just be `/some/log/gro` then it will succeed.

**Expected behavior**
Behavior should match docs

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.1.0]
1.4.3

- [ ] Was the solution modified from the version published on this repository?   No

- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? No
- [ ] Were there any errors in the CloudWatch Logs? No

**Additional context**
According to the [docs](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.CloudWatchLogsConfig.html) I should be able to use a wildcard.  Removing the wildcard character fixed the issue for me.  
I dug a bit in the code and found this line which I suspect is the culprit.  [see here](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/constructs/lib/aws-firehose/firehose-record-processing/index.ts#L128)

**Comment by padebnat** [comment] 2023-10-17 18:09
Hello @mmacaula , 
Thank you for reaching out to the Landing Zone Accelerator team!
I wanted to let you know that we have added an item in our backlog to look into this issue.

Thank you for your support and interest of the LZA solution! I will leave this issue open should you have any follow-ups for the team, and we will update you when the issue is fixed.

**Comment by georgecaddick** [comment] 2024-03-19 10:44
+1. Have also found that the accelerator prefix in the dynamic partitioning doesn't work either which would be very helpful.

**Comment by dfevre** [comment] 2024-04-24 07:46
+1

**Comment by erwaxler** [comment] 2024-04-24 14:37
As an update for this issue, a fix for this bug has been implemented and will be included in our next release. I will keep this issue open until the release is available. Thank you again for bringing this to our attention!

**Comment by erwaxler** [comment] 2024-06-03 14:07
Hi @mmacaula , this has been included in our [v1.7.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.7.0) so I will be closing this issue. Thanks for supporting the Landing Zone Accelerator!

**Closed by erwaxler** 2024-06-03 14:07 UTC
Labels: bug, pending-release
