### ISSUE TITLE
"It's not you, it's us" error during initial log in after account creation

### ISSUE THREAD

**Issue by dawidcx3** [awslabs/landing-zone-accelerator-on-aws#135] opened 2023-04-28 11:43 UTC
**Describe the bug**
There is a root account created with usage of Landing Zone Accelerator. During pipeline run there was an email received from 
no-reply@login.awsapps.com with AWS access portal URL, username and invitation link. There is no possibility to accept the invitation because every time it says:
"It's not you, it's us

We couldn't complete your request right now. Please try again later." and it's impossible to create the credentials.

Multiple tries didn't help and the error still occurs.

**To Reproduce**
Clicking the link causes the same error every time.

**Screenshots**
![image](https://user-images.githubusercontent.com/73645415/235138895-11e54759-c5a5-478d-9efe-158c70206f1b.png)

Thanks

**Comment by awsclemj** [comment] 2023-05-01 13:59
Hello @dawidcx3, and thank you for your interest in Landing Zone Accelerator on AWS!

When you say the root account, are you referring to the AWS Organizations/Control Tower Management Account? If so, the LZA solution does not manage the provisioning of that account, however the solution can manage the provisioning of additional member (also known as workload) accounts. The provisioning of the [mandatory accounts](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/mandatory-accounts.html) for the solution is managed either by AWS Organizations or AWS Control Tower, depending on what multi-account management solution you've decided to use in your environment.  

If there was an issue provisioning a member/workload account, you would have received an error [similar to the following](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/problem-account-enrollment-and-environment-validation-failures.html#general-account-enrollment-failure) during your pipeline run. Did you receive such an error? 

Regarding this particular error you are receiving, I would advise clearing your browser cache, trying a different web browser, running through the [sign-in troubleshooting steps](https://docs.aws.amazon.com/signin/latest/userguide/troubleshooting-sign-in-issues.html). If those steps do not help, I'd advise reaching out to AWS Support, who have the tools to help you further in this scenario. Based on what you've described, this seems to be related to the AWS web UI console login issue and not directly related to LZA account provisioning. 

Thank you, and please let us know if you have any follow-up questions!

**Comment by frankscalzo** [comment] 2023-05-02 12:48
@dawidcx3 

I had the same issue, for my design I used aliases of a distribution group that all come to my team.
 you can take that email address open the console in  private browser window or different browser and do the forgot password steps and it will send you a link than copy past that link into the the private window or other borwser and you will be able to create a password and login to that account.

hope that helps

Frank

**Comment by awsclemj** [comment] 2023-05-04 17:46
Hello, all!

Thank you for the follow-ups and additional detail here. I've done some searching through the documentation, and it appears that this is expected for accounts that are enrolled via AWS Organizations (which Control Tower uses in background). Since Landing Zone Accelerator utilizes the Control Tower Account Factory provisioning product, accounts provisioned for the solution will encounter the same error. 

Here is the document I referenced: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html#orgs_manage_accounts_access-as-root

If there is anything else I can help with, please feel free to update the issue. Otherwise, this seems to be expected behavior. Please feel free to close the issue if this procedure resolves the error.

Thanks again for your interest and support in our solution!

**Closed** 2023-05-25 20:26 UTC
Labels: bug

**Comment by yshollander-selerity** [comment] 2024-11-14 20:26
I opened a case today with AWS support after adding an account to ControlTower (account already in organization) and experiencing the same error.

If the account is already a member of the organization, and the Control Tower enrollment is successful, then why send a confirmation email at all?

This issue may have been closed prematurely.
