### ISSUE TITLE
Ability to tag all resources and individual resources in the config.

### ISSUE THREAD

**Issue by dannysteenman** [awslabs/landing-zone-accelerator-on-aws#225] opened 2023-08-03 06:48 UTC
**Describe the feature you'd like**
We've deployed this solution as part of the Migration Acceleration Program (MAP) from AWS. One of the requirements in this program is to tag all resources in an AWS account with a specific key. 

Would be nice to be able to tag all resources with a specific key/value.

Next to that it would also be great if we can tag resources seperately. For now it only seems that the vpc config (resources) can handle adding tags to its properties.

**Comment by DonthineniSagar** [comment] 2023-08-03 22:15
Yes, keen to have tagging feature which can be deployed to all the resources.

**Comment by erwaxler** [comment] 2023-08-07 18:23
I am closing this issue as a duplicate of #99. This feature will be released in the next major LZA release currently planned for the end of Q3.

**Closed by erwaxler** 2023-08-07 18:23 UTC
Labels: duplicate, enhancement

**Comment by anthony-sarkis-pwc** [comment] 2024-06-06 16:45
This issue has not been resolved
